// apps/owner-admin/src/OwnerAllowances.svelte
<script lang="ts">
  // D28 OwnerAllowances (design system v3.2, components/engagement/OwnerAllowances.jsx), ported to
  // Svelte with the approved copy. Master Off keeps the surface choices; Edge is shown as Deferred
  // and has no switch; nothing changes until Apply, and success is shown only after readback.
  import Toggle from "@still/core/ui/v3/Toggle.svelte";
  import StatusLine from "./StatusLine.svelte";
  import { APPROVED, PENDING_OWNER_COPY } from "./copy.js";
  import {
    changedAllowances,
    isDeferred,
    liveSurfaces,
    SURFACES,
    type AllowanceKey,
    type RatingModel,
    type Surface,
  } from "./policy-model.js";
  import { isBusy, type SectionState } from "./section-state.js";

  let {
    current,
    revision,
    phase = "idle",
    onApply,
    onRollback,
    onStatusAction,
    onEdit,
  }: {
    current: RatingModel;
    revision: number;
    phase?: SectionState;
    onApply: (draft: RatingModel) => void;
    onRollback?: () => void;
    onStatusAction: (state: SectionState, draft: RatingModel) => void;
    onEdit?: () => void;
  } = $props();

  const copy = APPROVED.allowances;
  let edited = $state<RatingModel | null>(null);
  const draft = $derived(edited ?? current);
  const changed = $derived(changedAllowances(current, draft));
  const busy = $derived(isBusy(phase));
  const live = $derived(liveSurfaces(draft).map((s) => APPROVED.surfaces[s]));

  /** Called by the page after a verified apply or a reload: the draft is the server state again. */
  export function reset() {
    edited = null;
  }

  function set(key: AllowanceKey, value: boolean) {
    edited =
      key === "global"
        ? { ...draft, master: value }
        : { ...draft, surfaces: { ...draft.surfaces, [key]: value } };
    onEdit?.();
  }
  const isOn = (key: AllowanceKey) => (key === "global" ? draft.master : draft.surfaces[key as Surface]);

  const line = $derived.by(() => {
    switch (phase) {
      case "applying": return { tone: "pending" as const, text: copy.applying };
      case "readback": return { tone: "pending" as const, text: copy.readback };
      case "applied": return { tone: "success" as const, text: copy.applied };
      case "stale": return { tone: "caution" as const, text: copy.stale, action: copy.reload };
      case "failed": return { tone: "failed" as const, text: copy.failed, action: copy.tryAgain };
      case "unconfirmed": return { tone: "caution" as const, text: PENDING_OWNER_COPY.unconfirmed, action: copy.reload };
      default: return null;
    }
  });
  const rows = $derived<{ id: AllowanceKey; name: string; deferred: boolean; inactive: boolean }[]>([
    { id: "global", name: copy.all, deferred: false, inactive: false },
    ...SURFACES.map((s) => ({ id: s, name: APPROVED.surfaces[s], deferred: isDeferred(s), inactive: !draft.master })),
  ]);
</script>

<section class="card card-stack" aria-label={copy.title} data-revision={revision}>
  <div class="heading">
    <h2 class="card-title">{copy.title}</h2>
    <p class="card-body small">{copy.body}</p>
  </div>
  <div class="allow-list">
    {#each rows as row (row.id)}
      <div class="allow-row" data-inactive={row.inactive || undefined}>
        <div class="row-main">
          <span class="label"
            ><span id={"al-" + row.id}>{row.name}</span>{#if row.deferred}<span class="access-tag boxed"
                >{copy.deferred}</span
              >{:else if changed.includes(row.id)}<span class="access-tag boxed">{copy.changed}</span>{/if}</span
          >
        </div>
        {#if !row.deferred}
          <Toggle
            small
            checked={isOn(row.id)}
            disabled={busy}
            labelledBy={"al-" + row.id}
            onChange={(v) => set(row.id, v)}
          />
        {/if}
      </div>
    {/each}
  </div>
  <p class="allow-preview">
    {copy.previewLead}<strong>{live.length ? live.join(", ") : copy.previewNone}</strong>.
  </p>
  {#if line}
    <StatusLine
      tone={line.tone}
      text={line.text}
      actionLabel={line.action}
      onAction={() => onStatusAction(phase, draft)}
    />
  {/if}
  <div class="inline-actions">
    <button
      type="button"
      class="primary inline"
      disabled={!changed.length || busy}
      onclick={() => onApply(draft)}>{copy.apply}</button
    >
    {#if changed.length > 0 && !busy}
      <button type="button" class="link" onclick={() => { edited = null; onEdit?.(); }}>{copy.discard}</button>
    {:else if onRollback && revision >= 2 && !busy}
      <button type="button" class="link" onclick={onRollback}>{PENDING_OWNER_COPY.rollback}</button>
    {/if}
  </div>
</section>

<style>
  .heading { display: flex; flex-direction: column; gap: 2px; }
  .small { font-size: calc(13px * var(--text-scale, 1)); }
</style>

// docs/design/Still v3.1 redesign/source/components/engagement/OwnerAllowances.jsx
import React, { useState } from 'react';
import { Toggle } from '../controls/Toggle.jsx';
import { Button } from '../controls/Button.jsx';
import { StatusLine } from '../feedback/StatusLine.jsx';

const SURFACES = [
  { id: 'chrome', name: 'Chrome desktop' },
  { id: 'edge', name: 'Edge desktop', deferred: true },
  { id: 'firefox', name: 'Firefox desktop' },
  { id: 'firefox-android', name: 'Firefox Android' },
  { id: 'apple-mobile', name: 'Apple mobile host' },
  { id: 'apple-mac', name: 'Apple macOS host' },
];
const ST = {
  applying: ['pending', 'Applying…'],
  readback: ['pending', 'Reading back the saved allowances…'],
  applied: ['success', 'Applied and read back. The server matches.'],
  stale: ['caution', 'These changed since you loaded them. Reload to see the current state.', 'Reload'],
  failed: ['failed', "Apply didn't finish. Nothing changed.", 'Try again'],
};
const onOff = v => (v ? 'On' : 'Off');

export function OwnerAllowances({ surfaces = SURFACES, current = {}, draft: draftProp, onDraftChange, state = 'idle', onApply, onDiscard, onStatusAction, announce = true }) {
  const [inner, setInner] = useState(current);
  const draft = draftProp ?? inner;
  const set = (id, v) => { const d = { ...draft, [id]: v }; if (!draftProp) setInner(d); onDraftChange && onDraftChange(d); };
  const changed = ['global', ...surfaces.map(s => s.id)].filter(k => !!draft[k] !== !!current[k]);
  const busy = state === 'applying' || state === 'readback';
  const live = surfaces.filter(s => !s.deferred && draft.global && draft[s.id]).map(s => s.name);
  const st = ST[state];
  const Row = ({ id, name, deferred, inactive }) => (
    <div className="allow-row" data-inactive={inactive || undefined}>
      <div className="row-main">
        <span className="label"><span id={'al-' + id}>{name}</span>{deferred && <span className="access-tag boxed">Deferred</span>}{!deferred && changed.includes(id) && <span className="access-tag boxed">Changed</span>}</span>
      </div>
      {!deferred && <Toggle size="small" checked={!!draft[id]} onChange={v => set(id, v)} disabled={busy} labelledBy={'al-' + id} />}
    </div>
  );
  return (
    <section className="card card-stack" aria-label="Rating prompt allowances">
      <div style={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
        <h2 className="card-title">Rating prompt allowances</h2>
        <p className="card-body" style={{ fontSize: 'calc(13px * var(--text-scale, 1))' }}>Off everywhere until you allow it. Nothing changes until Apply.</p>
      </div>
      <div className="allow-list">
        <Row id="global" name="All surfaces" />
        {surfaces.map(s => <Row key={s.id} id={s.id} name={s.name} deferred={s.deferred} inactive={!draft.global} />)}
      </div>
      <p className="allow-preview">After Apply, prompts are allowed on {live.length ? <strong>{live.join(', ')}</strong> : <strong>no surfaces</strong>}.</p>
      {st && <StatusLine tone={st[0]} actionLabel={st[2]} onAction={onStatusAction} announce={announce}>{st[1]}</StatusLine>}
      <div className="inline-actions">
        <Button inline disabled={!changed.length || busy} onClick={onApply}>Apply</Button>
        {changed.length > 0 && !busy && <Button variant="link" onClick={() => { if (!draftProp) setInner(current); onDiscard && onDiscard(); }}>Discard changes</Button>}
      </div>
    </section>
  );
}
