// apps/owner-admin/src/StatusLine.svelte
<script lang="ts">
  // The design system's StatusLine (components/feedback/StatusLine.jsx), drawn with the shared
  // .status-line styles: a tone glyph, the line, and an optional action.
  import Glyph from "@still/core/ui/v3/Glyph.svelte";

  let {
    tone,
    text,
    actionLabel,
    onAction,
  }: {
    tone: "pending" | "success" | "caution" | "failed";
    text: string;
    actionLabel?: string;
    onAction?: () => void;
  } = $props();

  const glyph = $derived(
    tone === "success" ? "check" : tone === "pending" ? "spinner" : "alert",
  );
</script>

<div
  class="status-line"
  data-tone={tone}
  role={tone === "failed" ? "alert" : "status"}
  aria-live={tone === "failed" ? "assertive" : "polite"}
>
  <span class="glyph"><Glyph name={glyph} size={16} /></span>
  <div class="status-body">
    <span>{text}</span>
    {#if actionLabel && onAction}<button
        type="button"
        class="link status-action"
        onclick={onAction}>{actionLabel}</button
      >{/if}
  </div>
</div>

// docs/design/Still v3.1 redesign/source/components/feedback/StatusLine.jsx
import React from 'react';
import { Glyph } from '../controls/Glyph.jsx';

const G = { pending: 'spinner', success: 'check', failed: 'alert', caution: 'clock', info: null };

export function StatusLine({ tone = 'info', children, detail, actionLabel, onAction, announce = true }) {
  const role = !announce ? undefined : tone === 'failed' ? 'alert' : 'status';
  return (
    <div className="status-line" data-tone={tone} role={role}>
      {G[tone] && <span className="glyph"><Glyph name={G[tone]} size={16} /></span>}
      <div className="status-body">
        <span>{children}</span>
        {detail && <span className="muted" style={{ fontSize: 'calc(12.5px * var(--text-scale, 1))' }}>{detail}</span>}
        {actionLabel && <button type="button" className="link status-action" onClick={onAction}>{actionLabel}</button>}
      </div>
    </div>
  );
}
